{"name": "test02_app_article", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test03_app.TestApp object at 0x00000166B6A944E0>\n\n    def test02_app_article(self):\n        # 1、调用查询接口\n        r = self.app.api_app_article()\n        try:\n            # 2、断言\n>           Tools.common_assert(r, status_code=200)\n\nscripts\\test03_app.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tools.tools.Tools'>, response = <Response [404]>, status_code = 200\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法！\")\n        # 断言状态码\n        print(response)\n>       assert status_code == response.status_code\nE       AssertionError\n\ntools\\tools.py:23: AssertionError"}, "attachments": [{"name": "log", "source": "038646a5-f6d8-4883-8f07-e655d33d7785-attachment.txt", "type": "text/plain"}], "start": 1639903617286, "stop": 1639903617436, "uuid": "1134e0a6-1a41-4e61-9b31-346f76e59b86", "historyId": "1e883c73aac2203ce0282bdde970dda4", "testCaseId": "bf6271faf3a70f81891fa0c87ca1060b", "fullName": "scripts.test03_app.TestApp#test02_app_article", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test03_app"}, {"name": "subSuite", "value": "TestApp"}, {"name": "host", "value": "My-fzj-pc"}, {"name": "thread", "value": "14292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test03_app"}]}